# import = ["~/.config/alacritty/tokyo/night.toml"]
[terminal.shell]
program = "/bin/bash"
#args = ["-l", "-c", "zellij"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
decorations = "None"
dynamic_padding = true
option_as_alt = "Both"
# opacity = 0.9
# blur = true


[window.padding]
x = 8
y = 8

[font]
size = 14

[font.normal]
#family = "JetbrainsMono Nerd Font"
#family = "Cascadia Code NF"
family = "FiraCode Nerd Font Mono"

[general]

live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[terminal]
#family = "Maple Mono NF"

